stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "s6-archlinux"
  IMAGE_TAG: "latest"
  GITHUB_PROJECT: "p42/s6-archlinux-docker.git"

before_script:
  - docker info

build-master:
  tags:
    - docker
  stage: build
  script:
    - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
  only:
    - master

test-master:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /ci_tests/run_tests system
  only:
    - master

test:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${IMAGE_TAG}" /ci_tests/run_tests system
  except:
    - master

build:
  tags:
    - docker
  stage: build
  script:
    - docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .
  except:
    - master

deploy_to_github:
  tags:
    - docker
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_tags_to_github:
  tags:
    - docker
  stage: deploy
  script:
    - git push git@github.com:${GITHUB_PROJECT} master --tags
  only:
    - tags
